name: Gitee Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  repo-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: mevoyacasa/iptvsdmobile

      - name: Edit README for Gitee Raw Images
        run: |
          sed -i 's|github.com/mevoyacasa/iptvsdmobile/blob/main/|gitee.com/mevoyacasa/iptv/raw/main/|g' README.md
          
          git config --global user.name "Mirror Bot"
          git config --global user.email "bot@example.com"
          
          git add README.md
          git commit -m "Auto-fix: Update image paths to Gitee raw" || echo "No changes to commit"

      - name: Sync to Gitee
        env:
          G_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git remote remove gitee || true
          git remote add gitee https://mevoyacasa:${G_TOKEN}@gitee.com/mevoyacasa/iptv.git
          
          git push gitee HEAD:master --force --tags
          git push gitee HEAD:master --force --tags
